Update icons and move into asset library.

diff --git a/Scripts/convertImages b/Scripts/convertImages
--- a/Scripts/convertImages
+++ b/Scripts/convertImages
@@ -1,110 +1,129 @@
-#!/usr/bin/env bash
+#! /usr/bin/env bash
 source bashlib
 cd "${0%/*}/../Gorillas/Resources/Images"
+PATH+=:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin
+temp="${TMPDIR:-/tmp}/.$$.convertImages"
+mkdir "$temp" || err "Couldn't create temp directory." || return
+trap 'rmdir "$temp"' EXIT
+
+downsize() {
+    local from=$1 to=$2 size=${3:-50%}
+    convert "$from" -filter box -resize "$size" -unsharp 1x1+1+0.4 "$to"
+    pngcrush -d "$temp" -rem gAMA -rem cHRM -rem sRGB -rem iCCP "$to" && mv "$temp/"* "$to"
+}
 
 
-emit "Converting PVRs"
-    srcs=(
-#        fire
-#        smoke
-#        hole
-    )
-    weightings=(
-        linear
-        linear
-        perceptual
-    )
-    bpps=(
-        2
-        2
-        4
-    )
 
-    for i in "${!srcs[@]}"; do
-        src=../png/${srcs[i]}.png
-        weighting=${weightings[i]}
-        bpp=${bpps[i]}
+inf "Converting PVRs"
+srcs=(
+#   fire
+#   smoke
+#   hole
+)
+weightings=(
+    linear
+    linear
+    perceptual
+)
+bpps=(
+    2
+    2
+    4
+)
+for i in "${!srcs[@]}"; do
+    src=../png/${srcs[i]}.png
+    weighting=${weightings[i]}
+    bpp=${bpps[i]}
 
-        [[ -f $src ]] || {
-            emit -r "Couldn't find '$src'"
-            continue
-        }
+    [[ -f $src ]] || {
+        err "Couldn't find %s" "$src"
+        continue
+    }
 
-        dst=${src##*/}
-        emit "$dst (${bpp}bpp, $weighting)" --
-            texturetool -e PVRTC -f PVR \
-                --channel-weighting-linear --bits-per-pixel-2 \
-                -p "$dst" -o "${dst%.png}.pvr" "$src"
-        emit -$?
-    done
+    dst=${src##*/}
+    pinf "%s (%sbpp, %s)" "$dst" "$bpp" "$weighting"
+        texturetool -e PVRTC -f PVR \
+            --channel-weighting-linear --bits-per-pixel-2 \
+            -p "$dst" -o "${dst%.png}.pvr" "$src"
+    fnip
+done
 
 
-echo
-emit "Converting iTunesArtwork"
-    icons=(
-        [57]="Icon.png"
-        [114]="Icon@2x.png"
-        [72]="Icon-72.png"
-        [144]="Icon-72@2x.png"
-        [29]="Icon-Small.png"
-        [58]="Icon-Small@2x.png"
-        [50]="Icon-Small-50.png"
-        [100]="Icon-Small-50@2x.png"
-    )
 
-    for size in "${!icons[@]}"; do
-        file=${icons[size]}
+inf "Converting appiconsets"
+icons=(
+    [114]="Icon@2x.png"
+    [120]="Icon-60@2x.png"
+    [80]="Icon-40@2x.png"
+    [144]="Icon-72@2x.png"
+    [58]="Icon-Small@2x.png"
+    [100]="Icon-Small-50@2x.png"
+    [512]="iTunesArtwork"
+)
+for size in $(reverse "${!icons[@]}"); do
+    file=Images.xcassets/AppIcon.appiconset/${icons[size]}
 
-        if [[ "iTunesArtwork.png" -nt $file ]]; then
-            emit "$file ($size px)" --
-                    convert "iTunesArtwork.png" -resize "${size}x${size}" "$file"
-            emit -$?
+    if [[ "iTunesArtwork" -nt $file ]]; then
+        pinf "$file ($size px)"
+            downsize "iTunesArtwork" "$file" "${size}x${size}"
+        fnip
+    fi
+done
+
+
+
+inf "Populating iconsets"
+icons=(
+    "icon_512x512.png"
+    "icon_256x256@2x.png"
+    "icon_256x256.png"
+    "icon_128x128@2x.png"
+    "icon_128x128.png"
+    "icon_32x32@2x.png"
+    "icon_32x32.png"
+    "icon_16x16@2x.png"
+    "icon_16x16.png"
+)
+for iconset in {,*.xcassets/}*.iconset; do
+    echo "$iconset"
+    [[ -d $iconset ]] || continue
+
+    for dest in "${icons[@]}"; do
+        src=$iconset/icon_512x512@2x.png
+        dest=$iconset/$dest
+        IFS='_x@.' read _ _ points scale _ <<< "${dest##*/}"
+        [[ $scale = *[^[:digit:]]* ]] && scale=1
+        size=$(( points * scale ))
+
+        if [[ ! -e $dest || "$src" -nt "$dest" ]]; then
+            pinf "$src -> $dest ($size px)"
+                downsize "$src" "$dest" "$size"
+            fnip
         fi
     done
+done
 
 
-emit "Converting iTunesArtwork Lite"
-    icons=(
-        [57]="lite/Icon.png"
-        [114]="lite/Icon@2x.png"
-        [72]="lite/Icon-72.png"
-        [144]="lite/Icon-72@2x.png"
-        [29]="lite/Icon-Small.png"
-        [58]="lite/Icon-Small@2x.png"
-        [50]="lite/Icon-Small-50.png"
-        [100]="lite/Icon-Small-50@2x.png"
-    )
+hr
+inf "Converting @2x/-hd artwork"
+for file in ./**/*{@2x,-ipadhd,-hd}.png; do
+    inArray "${file##*/}" "${icons[@]}" && continue
+    [[ ! -e $file ]] && continue
 
-    for size in "${!icons[@]}"; do
-        file=${icons[size]}
+    dest=${file/@(@2x|-hd)}
+    dest=${dest/-ipadhd/-ipad}
 
-        if [[ "lite/iTunesArtwork.png" -nt $file ]]; then
-            emit "$file ($size px)" --
-                    convert "lite/iTunesArtwork.png" -resize "${size}x${size}" "$file"
+    if [[ $file = Default* ]]; then
+        read width height < <(identify -format '%w %h' "$file")
+        if (( width > height )); then
+            emit "Rotating $file" --
+                mogrify -rotate 90 "$file"
             emit -$?
         fi
-    done
-
-
-echo
-emit "Converting @2x/-hd artwork"
-    for file in {,lite/}!(Icon*){@2x,-ipadhd,-hd}.png; do
-        [[ ! -e $file ]] && continue
-
-        dest=${file/@(@2x|-hd)}
-        dest=${dest/-ipadhd/-ipad}
-
-        #if [[ $file = Default* ]]; then
-        #    read width height < <(identify -format '%w %h' "$file")
-        #    if (( width > height )); then
-        #        emit "Rotating $file" --
-        #            mogrify -rotate 90 "$file"
-        #        emit -$?
-        #    fi
-        #fi
-        if [[ ! -e $dest || "$file" -nt "$dest" ]]; then
-            emit "$dest" --
-                    convert "$file" -resize 50% "$dest"
-            emit -$?
-        fi
-    done
+    fi
+    if [[ ! -e $dest || "$dest" -ot "$file" ]]; then
+        pinf "$file -> $dest"
+            downsize "$file" "$dest"
+        fnip
+    fi
+done
